services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-test
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: emizor_test
      DB_USERNAME: dev
      DB_PASSWORD: devpass
    command: tail -f /dev/null
    networks:
      - test-network
  mysql:
    image: mysql:8.0
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: emizor_test
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - "3334:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - test-network
volumes:
  mysql_data:
networks:
  test-network:
    driver: bridge